---
- name: Create Devices within NetBox
  netbox.netbox.netbox_device:
    netbox_url: "{{ lookup('ansible.builtin.env', 'NETBOX_API') }}"
    netbox_token: "{{ lookup('ansible.builtin.env', 'NETBOX_TOKEN') }}"
    data: "{{ device }}"
    state: present
  loop: "{{ devices }}"
  loop_control: 
    loop_var: device
    label: "{{ device['name']}}"