device_type:
- manufacturer: Metz Connect
  model: 130920-BKKE
  slug: 130920-bkke
  part_number: 130920-BKKE
  u_height: 1
  is_full_depth: false
  comments: '[Keystone 19 inch module frame 1RU 24 port black unequipped, shielded
    ](https://media.metz-connect.com/files/171/Data_sheet_130920-BKKE.PDF)'
console_ports: []
interfaces: []
rear_ports:
- device_type: 130920-bkke
  name: '01'
  type: 110-punch
  positions: 1
- device_type: 130920-bkke
  name: '02'
  type: 110-punch
  positions: 1
- device_type: 130920-bkke
  name: '03'
  type: 110-punch
  positions: 1
- device_type: 130920-bkke
  name: '04'
  type: 110-punch
  positions: 1
- device_type: 130920-bkke
  name: '05'
  type: 110-punch
  positions: 1
- device_type: 130920-bkke
  name: '06'
  type: 110-punch
  positions: 1
- device_type: 130920-bkke
  name: '07'
  type: 110-punch
  positions: 1
- device_type: 130920-bkke
  name: 08
  type: 110-punch
  positions: 1
- device_type: 130920-bkke
  name: 09
  type: 110-punch
  positions: 1
- device_type: 130920-bkke
  name: '10'
  type: 110-punch
  positions: 1
- device_type: 130920-bkke
  name: '11'
  type: 110-punch
  positions: 1
- device_type: 130920-bkke
  name: '12'
  type: 110-punch
  positions: 1
- device_type: 130920-bkke
  name: '13'
  type: 110-punch
  positions: 1
- device_type: 130920-bkke
  name: '14'
  type: 110-punch
  positions: 1
- device_type: 130920-bkke
  name: '15'
  type: 110-punch
  positions: 1
- device_type: 130920-bkke
  name: '16'
  type: 110-punch
  positions: 1
- device_type: 130920-bkke
  name: '17'
  type: 110-punch
  positions: 1
- device_type: 130920-bkke
  name: '18'
  type: 110-punch
  positions: 1
- device_type: 130920-bkke
  name: '19'
  type: 110-punch
  positions: 1
- device_type: 130920-bkke
  name: '20'
  type: 110-punch
  positions: 1
- device_type: 130920-bkke
  name: '21'
  type: 110-punch
  positions: 1
- device_type: 130920-bkke
  name: '22'
  type: 110-punch
  positions: 1
- device_type: 130920-bkke
  name: '23'
  type: 110-punch
  positions: 1
- device_type: 130920-bkke
  name: '24'
  type: 110-punch
  positions: 1
front_ports:
- device_type: 130920-bkke
  name: '01'
  type: 8p8c
  rear_port_template: '01'
  rear_port_template_position: 1
- device_type: 130920-bkke
  name: '02'
  type: 8p8c
  rear_port_template: '02'
  rear_port_template_position: 1
- device_type: 130920-bkke
  name: '03'
  type: 8p8c
  rear_port_template: '03'
  rear_port_template_position: 1
- device_type: 130920-bkke
  name: '04'
  type: 8p8c
  rear_port_template: '04'
  rear_port_template_position: 1
- device_type: 130920-bkke
  name: '05'
  type: 8p8c
  rear_port_template: '05'
  rear_port_template_position: 1
- device_type: 130920-bkke
  name: '06'
  type: 8p8c
  rear_port_template: '06'
  rear_port_template_position: 1
- device_type: 130920-bkke
  name: '07'
  type: 8p8c
  rear_port_template: '07'
  rear_port_template_position: 1
- device_type: 130920-bkke
  name: 08
  type: 8p8c
  rear_port_template: 08
  rear_port_template_position: 1
- device_type: 130920-bkke
  name: 09
  type: 8p8c
  rear_port_template: 09
  rear_port_template_position: 1
- device_type: 130920-bkke
  name: '10'
  type: 8p8c
  rear_port_template: '10'
  rear_port_template_position: 1
- device_type: 130920-bkke
  name: '11'
  type: 8p8c
  rear_port_template: '11'
  rear_port_template_position: 1
- device_type: 130920-bkke
  name: '12'
  type: 8p8c
  rear_port_template: '12'
  rear_port_template_position: 1
- device_type: 130920-bkke
  name: '13'
  type: 8p8c
  rear_port_template: '13'
  rear_port_template_position: 1
- device_type: 130920-bkke
  name: '14'
  type: 8p8c
  rear_port_template: '14'
  rear_port_template_position: 1
- device_type: 130920-bkke
  name: '15'
  type: 8p8c
  rear_port_template: '15'
  rear_port_template_position: 1
- device_type: 130920-bkke
  name: '16'
  type: 8p8c
  rear_port_template: '16'
  rear_port_template_position: 1
- device_type: 130920-bkke
  name: '17'
  type: 8p8c
  rear_port_template: '17'
  rear_port_template_position: 1
- device_type: 130920-bkke
  name: '18'
  type: 8p8c
  rear_port_template: '18'
  rear_port_template_position: 1
- device_type: 130920-bkke
  name: '19'
  type: 8p8c
  rear_port_template: '19'
  rear_port_template_position: 1
- device_type: 130920-bkke
  name: '20'
  type: 8p8c
  rear_port_template: '20'
  rear_port_template_position: 1
- device_type: 130920-bkke
  name: '21'
  type: 8p8c
  rear_port_template: '21'
  rear_port_template_position: 1
- device_type: 130920-bkke
  name: '22'
  type: 8p8c
  rear_port_template: '22'
  rear_port_template_position: 1
- device_type: 130920-bkke
  name: '23'
  type: 8p8c
  rear_port_template: '23'
  rear_port_template_position: 1
- device_type: 130920-bkke
  name: '24'
  type: 8p8c
  rear_port_template: '24'
  rear_port_template_position: 1
power_ports: []
