device_type:
- manufacturer: DIGITUS
  model: Cable-Management-Panel
  slug: cable-management-panel
  part_number: DN-97617
  u_height: 1
  is_full_depth: false
  comments: '[DIGITUS Cable Management Panel with detachable cover for 483 mm (19“)
    cabinets, 1U ](https://www.assmann.com/product-pdf/4016032279211?PL=en)'
console_ports: []
interfaces: []
rear_ports: []
front_ports: []
power_ports: []
