device_type:
- manufacturer: Cisco
  model: CBS220-48T-4G
  slug: cisco-cbs220-48-4g
  part_number: CBS220-48T-4G
  comments: https://www.cisco.com/c/en/us/products/collateral/switches/business-220-series-smart-switches/datasheet-c78-744915.html
  is_full_depth: false
  u_height: 1
console_ports:
- device_type: cisco-cbs220-48-4g
  name: con0
  type: rj-45
interfaces:
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet1
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet2
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet3
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet4
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet5
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet6
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet7
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet8
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet9
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet10
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet11
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet12
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet13
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet14
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet15
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet16
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet17
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet18
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet19
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet20
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet21
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet22
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet23
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet24
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet25
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet26
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet27
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet28
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet29
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet30
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet31
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet32
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet33
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet34
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet35
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet36
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet37
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet38
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet39
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet40
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet41
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet42
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet43
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet44
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet45
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet46
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet47
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet48
  type: 1000base-t
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet49
  type: 1000base-x-sfp
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet50
  type: 1000base-x-sfp
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet51
  type: 1000base-x-sfp
- device_type: cisco-cbs220-48-4g
  name: GigabitEthernet52
  type: 1000base-x-sfp
- device_type: cisco-cbs220-48-4g
  name: Port-Channel1
  type: lag
- device_type: cisco-cbs220-48-4g
  name: Port-Channel2
  type: lag
- device_type: cisco-cbs220-48-4g
  name: Port-Channel3
  type: lag
- device_type: cisco-cbs220-48-4g
  name: Port-Channel4
  type: lag
- device_type: cisco-cbs220-48-4g
  name: Port-Channel5
  type: lag
- device_type: cisco-cbs220-48-4g
  name: Port-Channel6
  type: lag
- device_type: cisco-cbs220-48-4g
  name: Port-Channel7
  type: lag
- device_type: cisco-cbs220-48-4g
  name: Port-Channel8
  type: lag
- device_type: cisco-cbs220-48-4g
  name: Vlan1
  type: virtual
rear_ports: []
front_ports: []
power_ports:
- device_type: cisco-cbs220-48-4g
  name: PSU0
  type: iec-60320-c14
  maximum_draw: 36
